name: envburn
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.2.5
  - geopandas=1.0.1
  - geodatasets=2024.8.0
  - cartopy=0.22.0
  - shapely=2.0.5
  - leafmap=0.38.5
  - boto3=1.35.78
  - botocore=1.35.78
  - dask=2024.9.1
  - dask-labextension
  - distributed=2024.9.1
  - dask-geopandas=0.4.2
  - matplotlib
  - geemap=0.35.1
  - requests_cache=0.4.13
  - pip=24.3.1
  - pip:
      - openmeteo-requests==1.3.0
      - retry_requests==2.0.0
      - load-dotenv==0.1.0
